### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tony-wuhongtao** [longtranista/django-vue-webpack#4]
When  npm run dev
I got this error info:

ERROR in ./assets/js/src/main.js

  ✘  http://eslint.org/docs/rules/  Parsing error: The keyword 'import' is reserved
      .... \django-vue-webpack\assets\js\src\main.js:1:1
  import Vue from 'vue'
   ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/null

**Comment by longtranista** [comment]
This code is quite old, From vue 1.x.x 
I will update new code very soon!

**Comment by longtranista** [comment]
Souce code updated!
