### ISSUE TITLE
How can I use server side rendering?

### ISSUE THREAD

**Issue by tagmetag** [longtranista/django-vue-webpack#7]
I set up for my project, It work correctly. Now I want to use server side rendering. Anyone can contribute this project?

**Comment by longtranista** [comment]
For the server side rendering, you can read more in Vue's official documentation. 
https://vuejs.org/v2/guide/ssr.html
Basically you have to you node js server to render on the server side, so it is not related to Django framework. 

Regards,

**Comment by tagmetag** [comment]
Mình để ý bạn là người Việt,
Bạn có thể gợi ý mình xíu về SSR cho dự án này không, thật sự mình mò cả tháng rồi mà kg chạy dc SSR :(
